# Generated by Django 4.0.5 on 2023-09-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_number', models.CharField(max_length=20)),
                ('complainant_name', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('ipc_applied', models.CharField(max_length=20)),
                ('pdf_fir', models.FileField(upload_to='fir_pdfs/')),
            ],
        ),
    ]
